# permissions for end users to view minecraftservergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftservergroup-viewer-role
rules:
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftservergroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftservergroups/status
  verbs:
  - get
