# permissions for end users to edit minecraftserverinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftserverinstance-editor-role
rules:
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftserverinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftserverinstances/status
  verbs:
  - get
