# permissions for end users to view minecraftproxydeployments.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftproxydeployment-viewer-role
rules:
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftproxydeployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftproxydeployments/status
  verbs:
  - get
