# permissions for end users to edit minecraftservergroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftservergroup-editor-role
rules:
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftservergroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftservergroups/status
  verbs:
  - get
