# permissions for end users to view minecraftserverinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftserverinstance-viewer-role
rules:
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftserverinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minecraft.minestack.io
  resources:
  - minecraftserverinstances/status
  verbs:
  - get
