bases:
  - ../default

resources: []

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: minestack-operator-controller-manager
      namespace: minestack-operator-system
    spec:
      strategy:
        type: Recreate
      template:
        spec:
          containers:
            - name: manager
              args: []
