apiVersion: minecraft.minestack.io/v1alpha1
kind: MinecraftServerDeployment
metadata:
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      image: ttl.sh/minestack/papermc-f8cefdfa-0527-41c8-86d4-98382d7dbbc8:24h
      resources:
        requests:
          cpu: 1
          memory: 4Gi
        limits:
          cpu: 1
          memory: 4Gi
      JVMHeap: 2Gi
