apiVersion: minecraft.minestack.io/v1alpha1
kind: MinecraftProxyDeployment
metadata:
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      labels:
        app: sample
    spec:
      image: ttl.sh/minestack/velocity-910bd61c-b125-415f-bce2-1ecc5f31b4aa:24h
      resources:
        requests:
          cpu: 200m
          memory: 1Gi
        limits:
          cpu: 200m
          memory: 1Gi
      JVMHeap: 512Mi
      serverGroups:
        - name: sample
          selector:
            matchLabels:
              app: sample
